### ISSUE TITLE
Patch for /bin/ExtractGName.R

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shenlab-sinai/ngsplot#40]
```
Allow for easy running
```

Original issue reported on code.google.com by `rjgunn...@gmail.com` on 12 Mar 2015 at 3:29

Attachments:
* [ExtractGName.R.patch](https://storage.googleapis.com/google-code-attachments/ngsplot/issue-40/comment-0/ExtractGName.R.patch)

**Comment by RGunning** [comment]
fixed by #45
