### ISSUE TITLE
Custom region for hg19

### ISSUE THREAD

**Issue by fpichon** [shenlab-sinai/ngsplot#43]
Hello, 

Congratulations for you really good software ! It helps a lot ! But now, I would like to create a new region, that is not really a genomic region but sites of viral integration. But the principle is same. 
How can I do ?
Thanks,

Fabien

**Comment by lishen** [comment]
Use bed files:
https://github.com/shenlab-sinai/ngsplot/wiki/HowToUseConfiguration
https://github.com/shenlab-sinai/ngsplot/wiki/HowToCreateBed
