### ISSUE TITLE
-RR (reduce ratio) parameter

### ISSUE THREAD

**Issue by igordot** [shenlab-sinai/ngsplot#53]
This is the documentation explanation:
```
    -RR  Reduce ratio(default=30). The parameter controls the heatmap height
           The smaller the value, the taller the heatmap
```
What exactly is it a ratio of?

**Comment by lishen** [comment]
The #of rows vs. the #of columns represented by each pixel for your heatmap.

Li


On Fri, Nov 13, 2015 at 10:00 PM, igor <notifications@github.com> wrote:

> This is the documentation explanation:
>
>     -RR  Reduce ratio(default=30). The parameter controls the heatmap height
>            The smaller the value, the taller the heatmap
>
> What exactly is it a ratio of?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shenlab-sinai/ngsplot/issues/53>.
>



-- 
Li Shen, Ph.D. Computer Science
Associate Professor
Department of Neuroscience
Icahn School of Medicine at Mount Sinai
New York, NY 10029
#################
ngs.plot - the coolest NGS plotting tool: https://code.google.com/p/ngsplot/
Want ChIP-seq differential analysis? Use:
https://code.google.com/p/diffreps/

**Comment by lishen** [comment]
This kind of questions shall be posted on the discussion forum. The issues are used for bugs and enhancements.

**Comment by igordot** [comment]
Thank you for the clarification. I would classify this comment as an enhancement. Although this is not related to the code, documentation is also important.
