### ISSUE TITLE
BED vs BAM

### ISSUE THREAD

**Issue by gireeshkbogu** [shenlab-sinai/ngsplot#70]
Hi,

How could I run ngsplot on BED format instead of BAM?
Ex:
chr1    10147   10183   N       1000    -
chr1    10159   10195   N       1000    -
chr1    10317   10353   N       1000    +
chr1    10496   10532   N       1000    +

FYI:
All ROADMAP epigenetic data (tagalign) has been stored in BED format. It would greatly useful if there is a way to plot this public data using your tool. thanks
http://egg2.wustl.edu/roadmap/data/byFileType/alignments/unconsolidated/H3K4me3/

**Comment by ny-shao** [comment]
Hi gireeshkbogu,

I would suggest giving bedtobam of bedtools a try:
http://bedtools.readthedocs.io/en/latest/content/tools/bedtobam.html
Don't forget to set -mpaq to 254 instead of the default 255, as 255 is not a standard validated value in SAM criteria.

Ning-Yi
